# Generated by Django 4.2.7 on 2023-12-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a_id', models.AutoField(db_column='a_id', primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=1024)),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_id', models.AutoField(db_column='c_id', primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('e_id', models.AutoField(db_column='e_id', primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('max_score', models.FloatField()),
            ],
            options={
                'db_table': 'exam',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('q_id', models.AutoField(db_column='q_id', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1026)),
                ('single_or_multi', models.CharField(choices=[('Single', 'Single'), ('Multi', 'Multi')], default='Single', max_length=8)),
                ('positive_score', models.IntegerField(default=1)),
                ('negative_score', models.IntegerField(default=0)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.course')),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('eq_id', models.AutoField(db_column='eq_id', primary_key=True, serialize=False)),
                ('e_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.exam')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.questions')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.answers')),
            ],
            options={
                'db_table': 'exam_questions',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.questions'),
        ),
    ]
